[tool.poetry]
name = "pygico-imagegen"
authors = [{name = "Your Name", email = "your.email@example.com"}]
description = "Python, GIMP, and ComfyUI based image generation and text addition tool"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["version", "dependencies"]
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "sphinx",
    "sphinx-rtd-theme",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"


[project.scripts]
pygico-imagegen = "pygico_imagegen.cli:main"

[tool.setuptools]
packages = ["pygico_imagegen"]
